### ISSUE TITLE
Turbolinks intergration

### ISSUE THREAD

**Issue by nsoseka** [jetthoughts/vuejs-rails-starterkit#23]
I find that in order for the `hello_vue` example to work as expected with turbolinks, i have to import
`import "initializers/turbolinks.js"`
In `hello_vue.js` and not `application.js`. 
or i load 
`<%= javascript_pack_tag 'application' %>`
from `application.html.erb`
I wonder why

**Comment by pftg** [comment]
@nsoseka thanks for found issue in README. In app I load initializers by adding extra include pack tag in layout https://github.com/jetthoughts/vuejs-rails-starterkit/commit/e2acacfcfa8d2983a46697e2ce5647c11a1e8fdd#diff-9599427925097c3c66f26ac1e0de5cad

Will update readme shortly

**Comment by nsoseka** [comment]
Okay great. Thanks for the prompt feedback. I will be closing this issue considering you will resolve it soon.
