### ISSUE TITLE
Error in step: Install Jest for Component Unit Tests

### ISSUE THREAD

**Issue by jcdescy** [jetthoughts/vuejs-rails-starterkit#38]
no matches found: babel-core@^7.0.0-bridge.0

From what I could google there seems to be some naming issues with Babel 7, but I'm not sure what the solution is. I tried babel-core@^7.0.0-0 as suggested elsewhere, but that didn't work either. Does command suggested here work for anyone?

**Comment by pftg** [comment]
Thanks, I'll check this in a moment. It worked 2 days ago.

**Comment by pftg** [comment]
Hey, @jcdescy could you give me reproduction steps and screenshots with your problem. I just rerun steps and this package is downloadable.

**Comment by jcdescy** [comment]
I do everything as laid out in the Readme here and everything works fine until I get to this step. Sadly "no matches found: babel-core@^7.0.0-bridge.0" is really all I get. I'm on a Mac, if this is helpful. 
 
From what I understand, this is a bridge between Babel 6 and Babel 7. Do I even need this, if I haven't worked with Babel before? Excuse the dumb question. I'm a backend guy and pretty new to frontend development.

**Comment by andriyParashchuk** [comment]
Hello, @jcdescy 
Works fine for me. 
MacOS
`node -v v14.4.0`
`yarn -v 1.22.4`
Shared screen fo you:
[![asciicast](https://asciinema.org/a/pbvDxQNsqq979ZHe4bceHeB7Q.svg)](https://asciinema.org/a/pbvDxQNsqq979ZHe4bceHeB7Q)

**Comment by andriyParashchuk** [comment]
Hello, @jcdescy 
I could not reproduce this error and therefore recorded a small video of how to create app step by step https://asciinema.org/a/ArqvGrc6JK6pKzlRTMV3Jotwr?t=8:44

**Comment by zilton7** [comment]
> no matches found: babel-core@^7.0.0-bridge.0
> 
> From what I could google there seems to be some naming issues with Babel 7, but I'm not sure what the solution is. I tried babel-core@^7.0.0-0 as suggested elsewhere, but that didn't work either. Does command suggested here work for anyone?

Did you manage to fix that? having the same issue... no matches found: babel-core@^7.0.0-bridge.0

**Comment by jcdescy** [comment]
No, sorry. I have no idea and sadly have no capacities to look into it any further. I switched to Laravel for several unrelated reasons. If there is something specific you want me to try or look at, I still have the project on my drive and I'd be glad to help. But as I said I currently have neither capacity nor reason to investigate this any further on my own.
